### ISSUE TITLE
How to reuse Selenium WebDriver instance?

### ISSUE THREAD

**Issue by Borisfrad** [PeterWippermann/parameterized-suite#2]
Hi,
You wrote there's an option to reuse a Selenium WebDriver instance, can you please provide a simple example?

Thanks!

**Comment by PeterWippermann** [comment]
Did you implement a method annotated with `@Parameters` that returns `Iterable<WebDriver>`? That's basically all you have to do.

Give it a try and share your code here. I'll be happy to comment it then :-)
