### ISSUE TITLE
Running multiple parameters for different Test cases

### ISSUE THREAD

**Issue by ThePickNick** [PeterWippermann/parameterized-suite#3]
Hi I was just wondering if there is a way to feed different parameters to a different test case for example I to first Test case in a I want to feed two parameters, and to the second class i want to feed 1 parameter. 

something like this 
```java
     @RunWith(ParameterizedSuite.class)
     @SuiteClasses({CreateRequest.class, DenyRequestAsRegionalEngineering.class })
     public class DenyRequestAsEegionalEngineeringSuite {
	
    @Parameters(name = "Parameters are {0} and {1}")
    public static Object[] params() {

        return new Object[][] {{"automatedtestsacct", "Regional Engineering (PA2)"}};

    }
	@Parameter(0)
	public String userName;	
	
	@Parameter(1)
	public String Approver;
    

    @Parameters(name = "test")
    public static Object[] paramsForDenyRequest(){
		return new  Object[][] {{"QARegionalBQ"}};
		}
	
	@Parameter(0)
	public String userNameEng;	
```
then grab the first set of parameters by the first test class and the second set by the second
is that possible?

**Comment by PeterWippermann** [comment]
Hi @ThePickNick,

thanks for your interest in this project! I'm always keen for feedback and questions :-)

I'm not sure whether I fully understood your use case: **Why would you combine** `CreateRequest` and `DenyRequestAsRegionalEngineering` in a single parameterized suite, **if they should not use the same parameters?** In your example you also only have one parameter (the array's size would be Object[1][2]).

**To answer your question: No, as of today that's not possible.** And I don't know how the execution logic should look like. Also, giving your `@Parameters` methods different names doesn't differentiate them for the test framework. It's just a display name and you may only have one parameters generating method per class.

Two possible options come to my mind:
### Option 1 - Combine multiple, independent test suites
You could have a parameterized suite for `CreateRequest` (and others?) and another parameterized suite for `DenyRequestAsRegionalEngineering` (and others?). Then combine those two suites in a regular `Suite`. I prepared an example: [TopLevelNoParametersSuite](https://github.com/PeterWippermann/parameterized-suite/blob/master/src/test/java/com/github/peterwippermann/junit4/parameterizedsuite/multiple_suites/TopLevelNoParametersSuite.java)

### Option 2 - Share the same parameter object but use different information from it
If you really want to have both (independent?) test cases in the same parameterized suite, you could introduce a parameter object holding all the information you need:
```java
public class UsernameAndApprover {
	private String userName;	
	private String Approver;
	private String userNameEng;

	// ... getters, setters, constructor
}
```

Define the parameters in the `ParameterizedSuite`:
```java
    @Parameters(name = "Current UsernameAndApprover is {0}")
    public static Object[] params() {

        return new Object[][] {
                {new UsernameAndApprover("automatedtestsacct", "Regional Engineering (PA2)", "QARegionalBQ")},
                {new UsernameAndApprover("another","triple","of parameters")}
        };
    }
```
Now in the `DenyRequestAsRegionalEngineering` test class you would only use the `userNameEng`:
```java
@Parameter(0)
public UsernameAndApprover uaaParameter;

@Test
public void test denyRequestAsRegionalEngineering() {
    String userNameEng = uaaParameter.getUserNameEng();
    // ...
}
```

**Comment by ThePickNick** [comment]
Hi Peter,

The reason I'm asking for this capability is because the two test cases are
dependent on each other( that is why I use suite to combine them), meaning
the CreateOutageRequest generates the unique ID initializes variable  and
DenayOutageRequest grab this ID and perform operation on that ticket.

The problems comes in because 2 test cases uses different sets of
parameters starting from logins credentials. Unfortunately i cant combine
them in a "master suite" because i was planing to reuse the test cases in
different suites ( in perticular the CreateOutageRequest) as any other test
case that i wrote starting from denying to approving  requires ID. The
question come how to pass variables from suite into test cases so I would
be able to reuse test cases in different suite and grab the variables that
been assigned in suit. Your paramettized suite almost accomplish the thing
I need but it will need to be able to handle different set of parameters
and this parameters need to be accessed by perticular test cases in the
suite.

I guess can't make this test cases truly automated.

Thank you for the time to replay

**Comment by PeterWippermann** [comment]
Hi @ThePickNick ,

thanks for explaining the details.
Why not go for my option #2 then? Define a class that can carry your information (Credentials and ID) as inner state. Instantiate an object of that class in your @parameters method and pass it around between the different test cases. One test case can store information there and another can read it.

**Comment by PeterWippermann** [comment]
I would have loved to get some more feedback :-(

**Comment by ThePickNick** [comment]
Hey, your solution is good with setters and getters but it would not be
applicable for my case. As I'm heavily reuse test scripts with different
number of parameters. Instead I group the script that I use most heavily
and on them I use parameters and rest scripts have the hard coded
variables. It's good attempt to create suits that would execute data driven
process for dependent test scripts. But what I looking for is way beyond
junit scope.

I still use your implementation of paramettized suites as it still help me
with those heavily utilized scripts in many suites. Thank you for talking
time to create this.
