### ISSUE TITLE
Example for use of @ClassRule or @BeforeClass with ParameterizedSuite

### ISSUE THREAD

**Issue by mpumalanga** [PeterWippermann/parameterized-suite#4]
I can't get a ClassRule to work with my ParameterizedSuite class. Neither @BeforeClass nor @ClassRule get executed before Parameters method.

I tried declaring it in a test class and the suite class, neither did work. Could you please give an example as how to get this behaviour to work?

**Comment by mpumalanga** [comment]
I tested the behaviour of the Suite Runner with ClassRule and it works. If i switch @RunWith(Suite.class) with @RunWith(ParameterizedSuite.class) the ClassRule is ignored.

**Comment by PeterWippermann** [comment]
Hi @mpumalanga ,

regarding the execution order of annotations : The `ParameterizedSuite` runner will basically launch a `Suite` for every parameter. When such a Suite is run, the `ClassRule`s and the like should be evaluated.
So the method annotated with `@Parameters` will be called first, `@ClassRule` will be called later - for every parameter.

Does this match the behaviour you're seeing? Can you share same code please?

**Comment by mpumalanga** [comment]
Hi @PeterWippermann,

thanks for your answer. I guess my problem is that @Parameters always get's executed first. JUnit says that this is needed in order to be able to tell the IDE what count of tests it can expect. I tried setting a Suite wide accessible variable but could therefore not access it inside the @Parameters method. When i shift this logic into the @Parameters method of the ParameterizedTestSuite, all is good!
